FROM node:14.14.0-alpine
WORKDIR "/usr/app"
COPY package.json .
RUN npm install
COPY . .
CMD ["npm","run","dev"]
#nodemon (dev - in packages in json) will automatically reload the entire project if it sees any changes in the code
